namespace Sandbox;

internal static partial class Rules
{
	internal static string[] Numerics =
	[
		// Live in their own dll for some reason
		"System.Runtime.Numerics/System.Numerics.BigInteger*",
		"System.Runtime.Numerics/System.Numerics.Complex*",

		"System.Private.CoreLib/System.Numerics.IAdditionOperators*",
		"System.Private.CoreLib/System.Numerics.IAdditiveIdentity*",
		"System.Private.CoreLib/System.Numerics.IBinaryFloatingPointIeee754*",
		// "System.Private.CoreLib/System.Numerics.IBinaryInteger*", // NOT THREAD SAFE, CAN OOB WRITE
		"System.Private.CoreLib/System.Numerics.IBinaryNumber*",
		"System.Private.CoreLib/System.Numerics.IBitwiseOperators*",
		"System.Private.CoreLib/System.Numerics.IComparisonOperators*",
		"System.Private.CoreLib/System.Numerics.IDecrementOperators*",
		"System.Private.CoreLib/System.Numerics.IDivisionOperators*",
		"System.Private.CoreLib/System.Numerics.IEqualityOperators*",
		"System.Private.CoreLib/System.Numerics.IExponentialFunctions*",
		"System.Private.CoreLib/System.Numerics.IFloatingPoint*",
		"System.Private.CoreLib/System.Numerics.IFloatingPointConstants*",
		"System.Private.CoreLib/System.Numerics.IFloatingPointIeee754*",
		"System.Private.CoreLib/System.Numerics.IHyperbolicFunctions*",
		"System.Private.CoreLib/System.Numerics.IIncrementOperators*",
		"System.Private.CoreLib/System.Numerics.ILogarithmicFunctions*",
		"System.Private.CoreLib/System.Numerics.IMinMaxValue*",
		"System.Private.CoreLib/System.Numerics.IModulusOperators*",
		"System.Private.CoreLib/System.Numerics.IMultiplicativeIdentity*",
		"System.Private.CoreLib/System.Numerics.IMultiplyOperators*",
		"System.Private.CoreLib/System.Numerics.INumber*",
		"System.Private.CoreLib/System.Numerics.INumberBase*",
		"System.Private.CoreLib/System.Numerics.IPowerFunctions*",
		"System.Private.CoreLib/System.Numerics.IRootFunctions*",
		"System.Private.CoreLib/System.Numerics.IShiftOperators*",
		"System.Private.CoreLib/System.Numerics.ISignedNumber*",
		"System.Private.CoreLib/System.Numerics.ISubtractionOperators*",
		"System.Private.CoreLib/System.Numerics.ITrigonometricFunctions*",
		"System.Private.CoreLib/System.Numerics.IUnaryNegationOperators*",
		"System.Private.CoreLib/System.Numerics.IUnaryPlusOperators*",
		"System.Private.CoreLib/System.Numerics.IUnsignedNumber*",

		"System.Private.CoreLib/System.Numerics.BitOperations*",
		"System.Private.CoreLib/System.Numerics.Matrix3x2*",
		"System.Private.CoreLib/System.Numerics.Matrix4x4*",
		"System.Private.CoreLib/System.Numerics.Plane*",
		"System.Private.CoreLib/System.Numerics.Quaternion*",

		//
		// Vector2
		//
		"System.Private.CoreLib/System.Numerics.Vector2",
		"System.Private.CoreLib/System.Numerics.Vector2..ctor( System.Single )",
		"System.Private.CoreLib/System.Numerics.Vector2..ctor( System.Single, System.Single )",
		"System.Private.CoreLib/System.Numerics.Vector2.get_Item( System.Int32 )",
		"System.Private.CoreLib/System.Numerics.Vector2.set_Item( System.Int32, System.Single )",
		"System.Private.CoreLib/System.Numerics.Vector2.CopyTo( System.Single[] )",
		"System.Private.CoreLib/System.Numerics.Vector2.CopyTo( System.Single[], System.Int32 )",
		"System.Private.CoreLib/System.Numerics.Vector2.Equals( System.Object )",
		"System.Private.CoreLib/System.Numerics.Vector2.Equals( System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.GetHashCode()",
		"System.Private.CoreLib/System.Numerics.Vector2.Length()",
		"System.Private.CoreLib/System.Numerics.Vector2.LengthSquared()",
		"System.Private.CoreLib/System.Numerics.Vector2.ToString()",
		"System.Private.CoreLib/System.Numerics.Vector2.ToString( System.String )",
		"System.Private.CoreLib/System.Numerics.Vector2.ToString( System.String, System.IFormatProvider )",
		"System.Private.CoreLib/System.Numerics.Vector2.get_AllBitsSet()",
		"System.Private.CoreLib/System.Numerics.Vector2.get_E()",
		"System.Private.CoreLib/System.Numerics.Vector2.get_Epsilon()",
		"System.Private.CoreLib/System.Numerics.Vector2.get_NaN()",
		"System.Private.CoreLib/System.Numerics.Vector2.get_NegativeInfinity()",
		"System.Private.CoreLib/System.Numerics.Vector2.get_NegativeZero()",
		"System.Private.CoreLib/System.Numerics.Vector2.get_One()",
		"System.Private.CoreLib/System.Numerics.Vector2.get_Pi()",
		"System.Private.CoreLib/System.Numerics.Vector2.get_PositiveInfinity()",
		"System.Private.CoreLib/System.Numerics.Vector2.get_Tau()",
		"System.Private.CoreLib/System.Numerics.Vector2.get_UnitX()",
		"System.Private.CoreLib/System.Numerics.Vector2.get_UnitY()",
		"System.Private.CoreLib/System.Numerics.Vector2.get_Zero()",
		"System.Private.CoreLib/System.Numerics.Vector2.op_Addition( System.Numerics.Vector2, System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.op_Division( System.Numerics.Vector2, System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.op_Division( System.Numerics.Vector2, System.Single )",
		"System.Private.CoreLib/System.Numerics.Vector2.op_Equality( System.Numerics.Vector2, System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.op_Inequality( System.Numerics.Vector2, System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.op_Multiply( System.Numerics.Vector2, System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.op_Multiply( System.Numerics.Vector2, System.Single )",
		"System.Private.CoreLib/System.Numerics.Vector2.op_Multiply( System.Single, System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.op_Subtraction( System.Numerics.Vector2, System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.op_UnaryNegation( System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.op_BitwiseAnd( System.Numerics.Vector2, System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.op_BitwiseOr( System.Numerics.Vector2, System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.op_ExclusiveOr( System.Numerics.Vector2, System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.op_LeftShift( System.Numerics.Vector2, System.Int32 )",
		"System.Private.CoreLib/System.Numerics.Vector2.op_OnesComplement( System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.op_RightShift( System.Numerics.Vector2, System.Int32 )",
		"System.Private.CoreLib/System.Numerics.Vector2.op_UnaryPlus( System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.op_UnsignedRightShift( System.Numerics.Vector2, System.Int32 )",
		"System.Private.CoreLib/System.Numerics.Vector2.Abs( System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.Add( System.Numerics.Vector2, System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.All( System.Numerics.Vector2, System.Single )",
		"System.Private.CoreLib/System.Numerics.Vector2.AllWhereAllBitsSet( System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.AndNot( System.Numerics.Vector2, System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.Any( System.Numerics.Vector2, System.Single )",
		"System.Private.CoreLib/System.Numerics.Vector2.AnyWhereAllBitsSet( System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.BitwiseAnd( System.Numerics.Vector2, System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.BitwiseOr( System.Numerics.Vector2, System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.Clamp( System.Numerics.Vector2, System.Numerics.Vector2, System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.ClampNative( System.Numerics.Vector2, System.Numerics.Vector2, System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.ConditionalSelect( System.Numerics.Vector2, System.Numerics.Vector2, System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.CopySign( System.Numerics.Vector2, System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.Cos( System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.Count( System.Numerics.Vector2, System.Single )",
		"System.Private.CoreLib/System.Numerics.Vector2.CountWhereAllBitsSet( System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.Create( System.Single )",
		"System.Private.CoreLib/System.Numerics.Vector2.Create( System.Single, System.Single )",
		"System.Private.CoreLib/System.Numerics.Vector2.Create( System.ReadOnlySpan`1[[System.Single, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]] )",
		"System.Private.CoreLib/System.Numerics.Vector2.CreateScalar( System.Single )",
		"System.Private.CoreLib/System.Numerics.Vector2.CreateScalarUnsafe( System.Single )",
		"System.Private.CoreLib/System.Numerics.Vector2.Cross( System.Numerics.Vector2, System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.DegreesToRadians( System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.Distance( System.Numerics.Vector2, System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.DistanceSquared( System.Numerics.Vector2, System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.Divide( System.Numerics.Vector2, System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.Divide( System.Numerics.Vector2, System.Single )",
		"System.Private.CoreLib/System.Numerics.Vector2.Dot( System.Numerics.Vector2, System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.Exp( System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.Equals( System.Numerics.Vector2, System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.EqualsAll( System.Numerics.Vector2, System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.EqualsAny( System.Numerics.Vector2, System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.FusedMultiplyAdd( System.Numerics.Vector2, System.Numerics.Vector2, System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.GreaterThan( System.Numerics.Vector2, System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.GreaterThanAll( System.Numerics.Vector2, System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.GreaterThanAny( System.Numerics.Vector2, System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.GreaterThanOrEqual( System.Numerics.Vector2, System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.GreaterThanOrEqualAll( System.Numerics.Vector2, System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.GreaterThanOrEqualAny( System.Numerics.Vector2, System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.Hypot( System.Numerics.Vector2, System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.IndexOf( System.Numerics.Vector2, System.Single )",
		"System.Private.CoreLib/System.Numerics.Vector2.IndexOfWhereAllBitsSet( System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.IsEvenInteger( System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.IsFinite( System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.IsInfinity( System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.IsInteger( System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.IsNaN( System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.IsNegative( System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.IsNegativeInfinity( System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.IsNormal( System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.IsOddInteger( System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.IsPositive( System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.IsPositiveInfinity( System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.IsSubnormal( System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.IsZero( System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.LastIndexOf( System.Numerics.Vector2, System.Single )",
		"System.Private.CoreLib/System.Numerics.Vector2.LastIndexOfWhereAllBitsSet( System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.Lerp( System.Numerics.Vector2, System.Numerics.Vector2, System.Single )",
		"System.Private.CoreLib/System.Numerics.Vector2.Lerp( System.Numerics.Vector2, System.Numerics.Vector2, System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.LessThan( System.Numerics.Vector2, System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.LessThanAll( System.Numerics.Vector2, System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.LessThanAny( System.Numerics.Vector2, System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.LessThanOrEqual( System.Numerics.Vector2, System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.LessThanOrEqualAll( System.Numerics.Vector2, System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.LessThanOrEqualAny( System.Numerics.Vector2, System.Numerics.Vector2 )",
		// "System.Private.CoreLib/System.Numerics.Vector2.Load( System.Single* )",
		// "System.Private.CoreLib/System.Numerics.Vector2.LoadAligned( System.Single* )",
		// "System.Private.CoreLib/System.Numerics.Vector2.LoadAlignedNonTemporal( System.Single* )",
		// "System.Private.CoreLib/System.Numerics.Vector2.LoadUnsafe( System.Single& )",
		// "System.Private.CoreLib/System.Numerics.Vector2.LoadUnsafe( System.Single&, System.UIntPtr )",
		"System.Private.CoreLib/System.Numerics.Vector2.Log( System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.Log2( System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.Max( System.Numerics.Vector2, System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.MaxMagnitude( System.Numerics.Vector2, System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.MaxMagnitudeNumber( System.Numerics.Vector2, System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.MaxNative( System.Numerics.Vector2, System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.MaxNumber( System.Numerics.Vector2, System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.Min( System.Numerics.Vector2, System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.MinMagnitude( System.Numerics.Vector2, System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.MinMagnitudeNumber( System.Numerics.Vector2, System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.MinNative( System.Numerics.Vector2, System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.MinNumber( System.Numerics.Vector2, System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.Multiply( System.Numerics.Vector2, System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.Multiply( System.Numerics.Vector2, System.Single )",
		"System.Private.CoreLib/System.Numerics.Vector2.Multiply( System.Single, System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.MultiplyAddEstimate( System.Numerics.Vector2, System.Numerics.Vector2, System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.Negate( System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.None( System.Numerics.Vector2, System.Single )",
		"System.Private.CoreLib/System.Numerics.Vector2.NoneWhereAllBitsSet( System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.Normalize( System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.OnesComplement( System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.RadiansToDegrees( System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.Reflect( System.Numerics.Vector2, System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.Round( System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.Round( System.Numerics.Vector2, System.MidpointRounding )",
		"System.Private.CoreLib/System.Numerics.Vector2.Shuffle( System.Numerics.Vector2, System.Byte, System.Byte )",
		"System.Private.CoreLib/System.Numerics.Vector2.Sin( System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.SinCos( System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.SquareRoot( System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.Subtract( System.Numerics.Vector2, System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.Sum( System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.Transform( System.Numerics.Vector2, System.Numerics.Matrix3x2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.Transform( System.Numerics.Vector2, System.Numerics.Matrix4x4 )",
		"System.Private.CoreLib/System.Numerics.Vector2.Transform( System.Numerics.Vector2, System.Numerics.Quaternion )",
		"System.Private.CoreLib/System.Numerics.Vector2.TransformNormal( System.Numerics.Vector2, System.Numerics.Matrix3x2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.TransformNormal( System.Numerics.Vector2, System.Numerics.Matrix4x4 )",
		"System.Private.CoreLib/System.Numerics.Vector2.Truncate( System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector2.Xor( System.Numerics.Vector2, System.Numerics.Vector2 )",

		//
		// Vector3
		//
		"System.Private.CoreLib/System.Numerics.Vector3",
		"System.Private.CoreLib/System.Numerics.Vector3..ctor( System.Single )",
		"System.Private.CoreLib/System.Numerics.Vector3..ctor( System.Numerics.Vector2, System.Single )",
		"System.Private.CoreLib/System.Numerics.Vector3..ctor( System.Single, System.Single, System.Single )",
		"System.Private.CoreLib/System.Numerics.Vector3.get_Item( System.Int32 )",
		"System.Private.CoreLib/System.Numerics.Vector3.set_Item( System.Int32, System.Single )",
		"System.Private.CoreLib/System.Numerics.Vector3.CopyTo( System.Single[] )",
		"System.Private.CoreLib/System.Numerics.Vector3.CopyTo( System.Single[], System.Int32 )",
		"System.Private.CoreLib/System.Numerics.Vector3.Equals( System.Object )",
		"System.Private.CoreLib/System.Numerics.Vector3.Equals( System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.GetHashCode()",
		"System.Private.CoreLib/System.Numerics.Vector3.Length()",
		"System.Private.CoreLib/System.Numerics.Vector3.LengthSquared()",
		"System.Private.CoreLib/System.Numerics.Vector3.ToString()",
		"System.Private.CoreLib/System.Numerics.Vector3.ToString( System.String )",
		"System.Private.CoreLib/System.Numerics.Vector3.ToString( System.String, System.IFormatProvider )",
		"System.Private.CoreLib/System.Numerics.Vector3.get_AllBitsSet()",
		"System.Private.CoreLib/System.Numerics.Vector3.get_E()",
		"System.Private.CoreLib/System.Numerics.Vector3.get_Epsilon()",
		"System.Private.CoreLib/System.Numerics.Vector3.get_NaN()",
		"System.Private.CoreLib/System.Numerics.Vector3.get_NegativeInfinity()",
		"System.Private.CoreLib/System.Numerics.Vector3.get_NegativeZero()",
		"System.Private.CoreLib/System.Numerics.Vector3.get_One()",
		"System.Private.CoreLib/System.Numerics.Vector3.get_Pi()",
		"System.Private.CoreLib/System.Numerics.Vector3.get_PositiveInfinity()",
		"System.Private.CoreLib/System.Numerics.Vector3.get_Tau()",
		"System.Private.CoreLib/System.Numerics.Vector3.get_UnitX()",
		"System.Private.CoreLib/System.Numerics.Vector3.get_UnitY()",
		"System.Private.CoreLib/System.Numerics.Vector3.get_UnitZ()",
		"System.Private.CoreLib/System.Numerics.Vector3.get_Zero()",
		"System.Private.CoreLib/System.Numerics.Vector3.op_Addition( System.Numerics.Vector3, System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.op_Division( System.Numerics.Vector3, System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.op_Division( System.Numerics.Vector3, System.Single )",
		"System.Private.CoreLib/System.Numerics.Vector3.op_Equality( System.Numerics.Vector3, System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.op_Inequality( System.Numerics.Vector3, System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.op_Multiply( System.Numerics.Vector3, System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.op_Multiply( System.Numerics.Vector3, System.Single )",
		"System.Private.CoreLib/System.Numerics.Vector3.op_Multiply( System.Single, System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.op_Subtraction( System.Numerics.Vector3, System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.op_UnaryNegation( System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.op_BitwiseAnd( System.Numerics.Vector3, System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.op_BitwiseOr( System.Numerics.Vector3, System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.op_ExclusiveOr( System.Numerics.Vector3, System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.op_LeftShift( System.Numerics.Vector3, System.Int32 )",
		"System.Private.CoreLib/System.Numerics.Vector3.op_OnesComplement( System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.op_RightShift( System.Numerics.Vector3, System.Int32 )",
		"System.Private.CoreLib/System.Numerics.Vector3.op_UnaryPlus( System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.op_UnsignedRightShift( System.Numerics.Vector3, System.Int32 )",
		"System.Private.CoreLib/System.Numerics.Vector3.Abs( System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.Add( System.Numerics.Vector3, System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.All( System.Numerics.Vector3, System.Single )",
		"System.Private.CoreLib/System.Numerics.Vector3.AllWhereAllBitsSet( System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.AndNot( System.Numerics.Vector3, System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.Any( System.Numerics.Vector3, System.Single )",
		"System.Private.CoreLib/System.Numerics.Vector3.AnyWhereAllBitsSet( System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.BitwiseAnd( System.Numerics.Vector3, System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.BitwiseOr( System.Numerics.Vector3, System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.Clamp( System.Numerics.Vector3, System.Numerics.Vector3, System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.ClampNative( System.Numerics.Vector3, System.Numerics.Vector3, System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.ConditionalSelect( System.Numerics.Vector3, System.Numerics.Vector3, System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.CopySign( System.Numerics.Vector3, System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.Cos( System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.Count( System.Numerics.Vector3, System.Single )",
		"System.Private.CoreLib/System.Numerics.Vector3.CountWhereAllBitsSet( System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.Create( System.Single )",
		"System.Private.CoreLib/System.Numerics.Vector3.Create( System.Numerics.Vector2, System.Single )",
		"System.Private.CoreLib/System.Numerics.Vector3.Create( System.Single, System.Single, System.Single )",
		"System.Private.CoreLib/System.Numerics.Vector3.CreateScalar( System.Single )",
		// "System.Private.CoreLib/System.Numerics.Vector3.CreateScalarUnsafe( System.Single )",
		"System.Private.CoreLib/System.Numerics.Vector3.Cross( System.Numerics.Vector3, System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.DegreesToRadians( System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.Distance( System.Numerics.Vector3, System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.DistanceSquared( System.Numerics.Vector3, System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.Divide( System.Numerics.Vector3, System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.Divide( System.Numerics.Vector3, System.Single )",
		"System.Private.CoreLib/System.Numerics.Vector3.Dot( System.Numerics.Vector3, System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.Exp( System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.Equals( System.Numerics.Vector3, System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.EqualsAll( System.Numerics.Vector3, System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.EqualsAny( System.Numerics.Vector3, System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.FusedMultiplyAdd( System.Numerics.Vector3, System.Numerics.Vector3, System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.GreaterThan( System.Numerics.Vector3, System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.GreaterThanAll( System.Numerics.Vector3, System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.GreaterThanAny( System.Numerics.Vector3, System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.GreaterThanOrEqual( System.Numerics.Vector3, System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.GreaterThanOrEqualAll( System.Numerics.Vector3, System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.GreaterThanOrEqualAny( System.Numerics.Vector3, System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.Hypot( System.Numerics.Vector3, System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.IndexOf( System.Numerics.Vector3, System.Single )",
		"System.Private.CoreLib/System.Numerics.Vector3.IndexOfWhereAllBitsSet( System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.IsEvenInteger( System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.IsFinite( System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.IsInfinity( System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.IsInteger( System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.IsNaN( System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.IsNegative( System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.IsNegativeInfinity( System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.IsNormal( System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.IsOddInteger( System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.IsPositive( System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.IsPositiveInfinity( System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.IsSubnormal( System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.IsZero( System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.LastIndexOf( System.Numerics.Vector3, System.Single )",
		"System.Private.CoreLib/System.Numerics.Vector3.LastIndexOfWhereAllBitsSet( System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.Lerp( System.Numerics.Vector3, System.Numerics.Vector3, System.Single )",
		"System.Private.CoreLib/System.Numerics.Vector3.Lerp( System.Numerics.Vector3, System.Numerics.Vector3, System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.LessThan( System.Numerics.Vector3, System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.LessThanAll( System.Numerics.Vector3, System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.LessThanAny( System.Numerics.Vector3, System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.LessThanOrEqual( System.Numerics.Vector3, System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.LessThanOrEqualAll( System.Numerics.Vector3, System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.LessThanOrEqualAny( System.Numerics.Vector3, System.Numerics.Vector3 )",
		// "System.Private.CoreLib/System.Numerics.Vector3.Load( System.Single* )",
		// "System.Private.CoreLib/System.Numerics.Vector3.LoadAligned( System.Single* )",
		// "System.Private.CoreLib/System.Numerics.Vector3.LoadAlignedNonTemporal( System.Single* )",
		// "System.Private.CoreLib/System.Numerics.Vector3.LoadUnsafe( System.Single& )",
		// "System.Private.CoreLib/System.Numerics.Vector3.LoadUnsafe( System.Single&, System.UIntPtr )",
		"System.Private.CoreLib/System.Numerics.Vector3.Log( System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.Log2( System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.Max( System.Numerics.Vector3, System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.MaxMagnitude( System.Numerics.Vector3, System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.MaxMagnitudeNumber( System.Numerics.Vector3, System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.MaxNative( System.Numerics.Vector3, System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.MaxNumber( System.Numerics.Vector3, System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.Min( System.Numerics.Vector3, System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.MinMagnitude( System.Numerics.Vector3, System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.MinMagnitudeNumber( System.Numerics.Vector3, System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.MinNative( System.Numerics.Vector3, System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.MinNumber( System.Numerics.Vector3, System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.Multiply( System.Numerics.Vector3, System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.Multiply( System.Numerics.Vector3, System.Single )",
		"System.Private.CoreLib/System.Numerics.Vector3.Multiply( System.Single, System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.MultiplyAddEstimate( System.Numerics.Vector3, System.Numerics.Vector3, System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.Negate( System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.None( System.Numerics.Vector3, System.Single )",
		"System.Private.CoreLib/System.Numerics.Vector3.NoneWhereAllBitsSet( System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.Normalize( System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.OnesComplement( System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.RadiansToDegrees( System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.Reflect( System.Numerics.Vector3, System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.Round( System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.Round( System.Numerics.Vector3, System.MidpointRounding )",
		"System.Private.CoreLib/System.Numerics.Vector3.Shuffle( System.Numerics.Vector3, System.Byte, System.Byte, System.Byte )",
		"System.Private.CoreLib/System.Numerics.Vector3.Sin( System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.SinCos( System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.SquareRoot( System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.Subtract( System.Numerics.Vector3, System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.Sum( System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.Transform( System.Numerics.Vector3, System.Numerics.Matrix4x4 )",
		"System.Private.CoreLib/System.Numerics.Vector3.Transform( System.Numerics.Vector3, System.Numerics.Quaternion )",
		"System.Private.CoreLib/System.Numerics.Vector3.TransformNormal( System.Numerics.Vector3, System.Numerics.Matrix4x4 )",
		"System.Private.CoreLib/System.Numerics.Vector3.Truncate( System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector3.Xor( System.Numerics.Vector3, System.Numerics.Vector3 )",

		//
		// Vector4
		//
		"System.Private.CoreLib/System.Numerics.Vector4",
		"System.Private.CoreLib/System.Numerics.Vector4..ctor( System.Single )",
		"System.Private.CoreLib/System.Numerics.Vector4..ctor( System.Numerics.Vector2, System.Single, System.Single )",
		"System.Private.CoreLib/System.Numerics.Vector4..ctor( System.Numerics.Vector3, System.Single )",
		"System.Private.CoreLib/System.Numerics.Vector4..ctor( System.Single, System.Single, System.Single, System.Single )",
		"System.Private.CoreLib/System.Numerics.Vector4.get_Item( System.Int32 )",
		"System.Private.CoreLib/System.Numerics.Vector4.set_Item( System.Int32, System.Single )",
		"System.Private.CoreLib/System.Numerics.Vector4.CopyTo( System.Single[] )",
		"System.Private.CoreLib/System.Numerics.Vector4.CopyTo( System.Single[], System.Int32 )",
		"System.Private.CoreLib/System.Numerics.Vector4.Equals( System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.Equals( System.Object )",
		"System.Private.CoreLib/System.Numerics.Vector4.GetHashCode()",
		"System.Private.CoreLib/System.Numerics.Vector4.Length()",
		"System.Private.CoreLib/System.Numerics.Vector4.LengthSquared()",
		"System.Private.CoreLib/System.Numerics.Vector4.ToString()",
		"System.Private.CoreLib/System.Numerics.Vector4.ToString( System.String )",
		"System.Private.CoreLib/System.Numerics.Vector4.ToString( System.String, System.IFormatProvider )",
		"System.Private.CoreLib/System.Numerics.Vector4.get_AllBitsSet()",
		"System.Private.CoreLib/System.Numerics.Vector4.get_E()",
		"System.Private.CoreLib/System.Numerics.Vector4.get_Epsilon()",
		"System.Private.CoreLib/System.Numerics.Vector4.get_NaN()",
		"System.Private.CoreLib/System.Numerics.Vector4.get_NegativeInfinity()",
		"System.Private.CoreLib/System.Numerics.Vector4.get_NegativeZero()",
		"System.Private.CoreLib/System.Numerics.Vector4.get_One()",
		"System.Private.CoreLib/System.Numerics.Vector4.get_Pi()",
		"System.Private.CoreLib/System.Numerics.Vector4.get_PositiveInfinity()",
		"System.Private.CoreLib/System.Numerics.Vector4.get_Tau()",
		"System.Private.CoreLib/System.Numerics.Vector4.get_UnitX()",
		"System.Private.CoreLib/System.Numerics.Vector4.get_UnitY()",
		"System.Private.CoreLib/System.Numerics.Vector4.get_UnitZ()",
		"System.Private.CoreLib/System.Numerics.Vector4.get_UnitW()",
		"System.Private.CoreLib/System.Numerics.Vector4.get_Zero()",
		"System.Private.CoreLib/System.Numerics.Vector4.op_Addition( System.Numerics.Vector4, System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.op_Division( System.Numerics.Vector4, System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.op_Division( System.Numerics.Vector4, System.Single )",
		"System.Private.CoreLib/System.Numerics.Vector4.op_Equality( System.Numerics.Vector4, System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.op_Inequality( System.Numerics.Vector4, System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.op_Multiply( System.Numerics.Vector4, System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.op_Multiply( System.Numerics.Vector4, System.Single )",
		"System.Private.CoreLib/System.Numerics.Vector4.op_Multiply( System.Single, System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.op_Subtraction( System.Numerics.Vector4, System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.op_UnaryNegation( System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.op_BitwiseAnd( System.Numerics.Vector4, System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.op_BitwiseOr( System.Numerics.Vector4, System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.op_ExclusiveOr( System.Numerics.Vector4, System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.op_LeftShift( System.Numerics.Vector4, System.Int32 )",
		"System.Private.CoreLib/System.Numerics.Vector4.op_OnesComplement( System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.op_RightShift( System.Numerics.Vector4, System.Int32 )",
		"System.Private.CoreLib/System.Numerics.Vector4.op_UnaryPlus( System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.op_UnsignedRightShift( System.Numerics.Vector4, System.Int32 )",
		"System.Private.CoreLib/System.Numerics.Vector4.Abs( System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.Add( System.Numerics.Vector4, System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.All( System.Numerics.Vector4, System.Single )",
		"System.Private.CoreLib/System.Numerics.Vector4.AllWhereAllBitsSet( System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.AndNot( System.Numerics.Vector4, System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.Any( System.Numerics.Vector4, System.Single )",
		"System.Private.CoreLib/System.Numerics.Vector4.AnyWhereAllBitsSet( System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.BitwiseAnd( System.Numerics.Vector4, System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.BitwiseOr( System.Numerics.Vector4, System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.Clamp( System.Numerics.Vector4, System.Numerics.Vector4, System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.ClampNative( System.Numerics.Vector4, System.Numerics.Vector4, System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.ConditionalSelect( System.Numerics.Vector4, System.Numerics.Vector4, System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.CopySign( System.Numerics.Vector4, System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.Cos( System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.Count( System.Numerics.Vector4, System.Single )",
		"System.Private.CoreLib/System.Numerics.Vector4.CountWhereAllBitsSet( System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.Create( System.Single )",
		"System.Private.CoreLib/System.Numerics.Vector4.Create( System.Numerics.Vector2, System.Single, System.Single )",
		"System.Private.CoreLib/System.Numerics.Vector4.Create( System.Numerics.Vector3, System.Single )",
		"System.Private.CoreLib/System.Numerics.Vector4.Create( System.Single, System.Single, System.Single, System.Single )",
		"System.Private.CoreLib/System.Numerics.Vector4.CreateScalar( System.Single )",
		// "System.Private.CoreLib/System.Numerics.Vector4.CreateScalarUnsafe( System.Single )",
		"System.Private.CoreLib/System.Numerics.Vector4.Cross( System.Numerics.Vector4, System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.DegreesToRadians( System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.Distance( System.Numerics.Vector4, System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.DistanceSquared( System.Numerics.Vector4, System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.Divide( System.Numerics.Vector4, System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.Divide( System.Numerics.Vector4, System.Single )",
		"System.Private.CoreLib/System.Numerics.Vector4.Dot( System.Numerics.Vector4, System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.Exp( System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.Equals( System.Numerics.Vector4, System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.EqualsAll( System.Numerics.Vector4, System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.EqualsAny( System.Numerics.Vector4, System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.FusedMultiplyAdd( System.Numerics.Vector4, System.Numerics.Vector4, System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.GreaterThan( System.Numerics.Vector4, System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.GreaterThanAll( System.Numerics.Vector4, System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.GreaterThanAny( System.Numerics.Vector4, System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.GreaterThanOrEqual( System.Numerics.Vector4, System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.GreaterThanOrEqualAll( System.Numerics.Vector4, System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.GreaterThanOrEqualAny( System.Numerics.Vector4, System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.Hypot( System.Numerics.Vector4, System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.IndexOf( System.Numerics.Vector4, System.Single )",
		"System.Private.CoreLib/System.Numerics.Vector4.IndexOfWhereAllBitsSet( System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.IsEvenInteger( System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.IsFinite( System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.IsInfinity( System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.IsInteger( System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.IsNaN( System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.IsNegative( System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.IsNegativeInfinity( System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.IsNormal( System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.IsOddInteger( System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.IsPositive( System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.IsPositiveInfinity( System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.IsSubnormal( System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.IsZero( System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.LastIndexOf( System.Numerics.Vector4, System.Single )",
		"System.Private.CoreLib/System.Numerics.Vector4.LastIndexOfWhereAllBitsSet( System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.Lerp( System.Numerics.Vector4, System.Numerics.Vector4, System.Single )",
		"System.Private.CoreLib/System.Numerics.Vector4.Lerp( System.Numerics.Vector4, System.Numerics.Vector4, System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.LessThan( System.Numerics.Vector4, System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.LessThanAll( System.Numerics.Vector4, System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.LessThanAny( System.Numerics.Vector4, System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.LessThanOrEqual( System.Numerics.Vector4, System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.LessThanOrEqualAll( System.Numerics.Vector4, System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.LessThanOrEqualAny( System.Numerics.Vector4, System.Numerics.Vector4 )",
		// "System.Private.CoreLib/System.Numerics.Vector4.Load( System.Single* )",
		// "System.Private.CoreLib/System.Numerics.Vector4.LoadAligned( System.Single* )",
		// "System.Private.CoreLib/System.Numerics.Vector4.LoadAlignedNonTemporal( System.Single* )",
		// "System.Private.CoreLib/System.Numerics.Vector4.LoadUnsafe( System.Single& )",
		// "System.Private.CoreLib/System.Numerics.Vector4.LoadUnsafe( System.Single&, System.UIntPtr )",
		"System.Private.CoreLib/System.Numerics.Vector4.Log( System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.Log2( System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.Max( System.Numerics.Vector4, System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.MaxMagnitude( System.Numerics.Vector4, System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.MaxMagnitudeNumber( System.Numerics.Vector4, System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.MaxNative( System.Numerics.Vector4, System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.MaxNumber( System.Numerics.Vector4, System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.Min( System.Numerics.Vector4, System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.MinMagnitude( System.Numerics.Vector4, System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.MinMagnitudeNumber( System.Numerics.Vector4, System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.MinNative( System.Numerics.Vector4, System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.MinNumber( System.Numerics.Vector4, System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.Multiply( System.Numerics.Vector4, System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.Multiply( System.Numerics.Vector4, System.Single )",
		"System.Private.CoreLib/System.Numerics.Vector4.Multiply( System.Single, System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.MultiplyAddEstimate( System.Numerics.Vector4, System.Numerics.Vector4, System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.Negate( System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.None( System.Numerics.Vector4, System.Single )",
		"System.Private.CoreLib/System.Numerics.Vector4.NoneWhereAllBitsSet( System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.Normalize( System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.OnesComplement( System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.RadiansToDegrees( System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.Round( System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.Round( System.Numerics.Vector4, System.MidpointRounding )",
		"System.Private.CoreLib/System.Numerics.Vector4.Shuffle( System.Numerics.Vector4, System.Byte, System.Byte, System.Byte, System.Byte )",
		"System.Private.CoreLib/System.Numerics.Vector4.Sin( System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.SinCos( System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.SquareRoot( System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.Subtract( System.Numerics.Vector4, System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.Sum( System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.Transform( System.Numerics.Vector2, System.Numerics.Matrix4x4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.Transform( System.Numerics.Vector2, System.Numerics.Quaternion )",
		"System.Private.CoreLib/System.Numerics.Vector4.Transform( System.Numerics.Vector3, System.Numerics.Matrix4x4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.Transform( System.Numerics.Vector3, System.Numerics.Quaternion )",
		"System.Private.CoreLib/System.Numerics.Vector4.Transform( System.Numerics.Vector4, System.Numerics.Matrix4x4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.Transform( System.Numerics.Vector4, System.Numerics.Quaternion )",
		"System.Private.CoreLib/System.Numerics.Vector4.Truncate( System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector4.Xor( System.Numerics.Vector4, System.Numerics.Vector4 )",

		//
		// Extension Methods
		//
		"System.Private.CoreLib/System.Numerics.Vector.AsVector4( System.Numerics.Plane )",
		"System.Private.CoreLib/System.Numerics.Vector.AsVector4( System.Numerics.Quaternion )",
		"System.Private.CoreLib/System.Numerics.Vector.AsVector3( System.Numerics.Vector2 )",
		// "System.Private.CoreLib/System.Numerics.Vector.AsVector3Unsafe( System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector.AsVector4( System.Numerics.Vector2 )",
		// "System.Private.CoreLib/System.Numerics.Vector.AsVector4Unsafe( System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector.ExtractMostSignificantBits( System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector.GetElement( System.Numerics.Vector2, System.Int32 )",
		// "System.Private.CoreLib/System.Numerics.Vector.Store( System.Numerics.Vector2, System.Single* )",
		// "System.Private.CoreLib/System.Numerics.Vector.StoreAligned( System.Numerics.Vector2, System.Single* )",
		// "System.Private.CoreLib/System.Numerics.Vector.StoreAlignedNonTemporal( System.Numerics.Vector2, System.Single* )",
		// "System.Private.CoreLib/System.Numerics.Vector.StoreUnsafe( System.Numerics.Vector2, System.Single& )",
		// "System.Private.CoreLib/System.Numerics.Vector.StoreUnsafe( System.Numerics.Vector2, System.Single&, System.UIntPtr )",
		"System.Private.CoreLib/System.Numerics.Vector.ToScalar( System.Numerics.Vector2 )",
		"System.Private.CoreLib/System.Numerics.Vector.WithElement( System.Numerics.Vector2, System.Int32, System.Single )",
		"System.Private.CoreLib/System.Numerics.Vector.AsVector2( System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector.AsVector4( System.Numerics.Vector3 )",
		// "System.Private.CoreLib/System.Numerics.Vector.AsVector4Unsafe( System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector.ExtractMostSignificantBits( System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector.GetElement( System.Numerics.Vector3, System.Int32 )",
		// "System.Private.CoreLib/System.Numerics.Vector.Store( System.Numerics.Vector3, System.Single* )",
		// "System.Private.CoreLib/System.Numerics.Vector.StoreAligned( System.Numerics.Vector3, System.Single* )",
		// "System.Private.CoreLib/System.Numerics.Vector.StoreAlignedNonTemporal( System.Numerics.Vector3, System.Single* )",
		// "System.Private.CoreLib/System.Numerics.Vector.StoreUnsafe( System.Numerics.Vector3, System.Single& )",
		// "System.Private.CoreLib/System.Numerics.Vector.StoreUnsafe( System.Numerics.Vector3, System.Single&, System.UIntPtr )",
		"System.Private.CoreLib/System.Numerics.Vector.ToScalar( System.Numerics.Vector3 )",
		"System.Private.CoreLib/System.Numerics.Vector.WithElement( System.Numerics.Vector3, System.Int32, System.Single )",
		"System.Private.CoreLib/System.Numerics.Vector.AsPlane( System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector.AsQuaternion( System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector.AsVector2( System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector.AsVector3( System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector.ExtractMostSignificantBits( System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector.GetElement( System.Numerics.Vector4, System.Int32 )",
		// "System.Private.CoreLib/System.Numerics.Vector.Store( System.Numerics.Vector4, System.Single* )",
		// "System.Private.CoreLib/System.Numerics.Vector.StoreAligned( System.Numerics.Vector4, System.Single* )",
		// "System.Private.CoreLib/System.Numerics.Vector.StoreAlignedNonTemporal( System.Numerics.Vector4, System.Single* )",
		// "System.Private.CoreLib/System.Numerics.Vector.StoreUnsafe( System.Numerics.Vector4, System.Single& )",
		// "System.Private.CoreLib/System.Numerics.Vector.StoreUnsafe( System.Numerics.Vector4, System.Single&, System.UIntPtr )",
		"System.Private.CoreLib/System.Numerics.Vector.ToScalar( System.Numerics.Vector4 )",
		"System.Private.CoreLib/System.Numerics.Vector.WithElement( System.Numerics.Vector4, System.Int32, System.Single )",
	];
}
